title: Pradip Krishnaa Murugan
url: "https://pradipkrishnaa.github.io"
baseurl: "https://pradipkrishnaa.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/pradipkrishnaa.github.io/"
 - name: "Work"
   link: "work"
 - name: "Resume"
   link: "resume.pdf"
